export const SCREEN_SPLASH = 'Splash';
export const SCREEN_PHONE_LOGIN = 'PhoneLogin';
export const SCREEN_OTP_VERIFICATION = 'OTPVerification';
export const SCREEN_VEHICLE_REGISTER = 'VehicleRegister';
export const SCREEN_ON_DRIVE = 'OnDrive';
export const SCREEN_HOME = 'Home';
export const screens = {
  KEY_SCREEN_SPLASH: SCREEN_SPLASH,
  KEY_SCREEN_PHONE_LOGIN: SCREEN_PHONE_LOGIN,
  KEY_SCREEN_OTP_VERIFICATION: SCREEN_OTP_VERIFICATION,
  KEY_SCREEN_VEHICLE_REGISTER: SCREEN_VEHICLE_REGISTER,
  KEY_SCREEN_ON_DRIVE: SCREEN_ON_DRIVE,
  KEY_SCREEN_HOME: SCREEN_HOME,
};
